package com.hoomsun.aoqian;

import java.util.ArrayList;
import java.util.List;

public class BreakonespromiseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public BreakonespromiseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andA1IsNull() {
            addCriterion("a1 is null");
            return (Criteria) this;
        }

        public Criteria andA1IsNotNull() {
            addCriterion("a1 is not null");
            return (Criteria) this;
        }

        public Criteria andA1EqualTo(String value) {
            addCriterion("a1 =", value, "a1");
            return (Criteria) this;
        }

        public Criteria andA1NotEqualTo(String value) {
            addCriterion("a1 <>", value, "a1");
            return (Criteria) this;
        }

        public Criteria andA1GreaterThan(String value) {
            addCriterion("a1 >", value, "a1");
            return (Criteria) this;
        }

        public Criteria andA1GreaterThanOrEqualTo(String value) {
            addCriterion("a1 >=", value, "a1");
            return (Criteria) this;
        }

        public Criteria andA1LessThan(String value) {
            addCriterion("a1 <", value, "a1");
            return (Criteria) this;
        }

        public Criteria andA1LessThanOrEqualTo(String value) {
            addCriterion("a1 <=", value, "a1");
            return (Criteria) this;
        }

        public Criteria andA1Like(String value) {
            addCriterion("a1 like", value, "a1");
            return (Criteria) this;
        }

        public Criteria andA1NotLike(String value) {
            addCriterion("a1 not like", value, "a1");
            return (Criteria) this;
        }

        public Criteria andA1In(List<String> values) {
            addCriterion("a1 in", values, "a1");
            return (Criteria) this;
        }

        public Criteria andA1NotIn(List<String> values) {
            addCriterion("a1 not in", values, "a1");
            return (Criteria) this;
        }

        public Criteria andA1Between(String value1, String value2) {
            addCriterion("a1 between", value1, value2, "a1");
            return (Criteria) this;
        }

        public Criteria andA1NotBetween(String value1, String value2) {
            addCriterion("a1 not between", value1, value2, "a1");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("Id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("Id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSourceidIsNull() {
            addCriterion("Sourceid is null");
            return (Criteria) this;
        }

        public Criteria andSourceidIsNotNull() {
            addCriterion("Sourceid is not null");
            return (Criteria) this;
        }

        public Criteria andSourceidEqualTo(String value) {
            addCriterion("Sourceid =", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotEqualTo(String value) {
            addCriterion("Sourceid <>", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidGreaterThan(String value) {
            addCriterion("Sourceid >", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidGreaterThanOrEqualTo(String value) {
            addCriterion("Sourceid >=", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidLessThan(String value) {
            addCriterion("Sourceid <", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidLessThanOrEqualTo(String value) {
            addCriterion("Sourceid <=", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidLike(String value) {
            addCriterion("Sourceid like", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotLike(String value) {
            addCriterion("Sourceid not like", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidIn(List<String> values) {
            addCriterion("Sourceid in", values, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotIn(List<String> values) {
            addCriterion("Sourceid not in", values, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidBetween(String value1, String value2) {
            addCriterion("Sourceid between", value1, value2, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotBetween(String value1, String value2) {
            addCriterion("Sourceid not between", value1, value2, "sourceid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLiandateIsNull() {
            addCriterion("Liandate is null");
            return (Criteria) this;
        }

        public Criteria andLiandateIsNotNull() {
            addCriterion("Liandate is not null");
            return (Criteria) this;
        }

        public Criteria andLiandateEqualTo(String value) {
            addCriterion("Liandate =", value, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateNotEqualTo(String value) {
            addCriterion("Liandate <>", value, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateGreaterThan(String value) {
            addCriterion("Liandate >", value, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateGreaterThanOrEqualTo(String value) {
            addCriterion("Liandate >=", value, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateLessThan(String value) {
            addCriterion("Liandate <", value, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateLessThanOrEqualTo(String value) {
            addCriterion("Liandate <=", value, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateLike(String value) {
            addCriterion("Liandate like", value, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateNotLike(String value) {
            addCriterion("Liandate not like", value, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateIn(List<String> values) {
            addCriterion("Liandate in", values, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateNotIn(List<String> values) {
            addCriterion("Liandate not in", values, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateBetween(String value1, String value2) {
            addCriterion("Liandate between", value1, value2, "liandate");
            return (Criteria) this;
        }

        public Criteria andLiandateNotBetween(String value1, String value2) {
            addCriterion("Liandate not between", value1, value2, "liandate");
            return (Criteria) this;
        }

        public Criteria andAnnoIsNull() {
            addCriterion("Anno is null");
            return (Criteria) this;
        }

        public Criteria andAnnoIsNotNull() {
            addCriterion("Anno is not null");
            return (Criteria) this;
        }

        public Criteria andAnnoEqualTo(String value) {
            addCriterion("Anno =", value, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoNotEqualTo(String value) {
            addCriterion("Anno <>", value, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoGreaterThan(String value) {
            addCriterion("Anno >", value, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoGreaterThanOrEqualTo(String value) {
            addCriterion("Anno >=", value, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoLessThan(String value) {
            addCriterion("Anno <", value, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoLessThanOrEqualTo(String value) {
            addCriterion("Anno <=", value, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoLike(String value) {
            addCriterion("Anno like", value, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoNotLike(String value) {
            addCriterion("Anno not like", value, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoIn(List<String> values) {
            addCriterion("Anno in", values, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoNotIn(List<String> values) {
            addCriterion("Anno not in", values, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoBetween(String value1, String value2) {
            addCriterion("Anno between", value1, value2, "anno");
            return (Criteria) this;
        }

        public Criteria andAnnoNotBetween(String value1, String value2) {
            addCriterion("Anno not between", value1, value2, "anno");
            return (Criteria) this;
        }

        public Criteria andBiaodiIsNull() {
            addCriterion("Biaodi is null");
            return (Criteria) this;
        }

        public Criteria andBiaodiIsNotNull() {
            addCriterion("Biaodi is not null");
            return (Criteria) this;
        }

        public Criteria andBiaodiEqualTo(String value) {
            addCriterion("Biaodi =", value, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiNotEqualTo(String value) {
            addCriterion("Biaodi <>", value, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiGreaterThan(String value) {
            addCriterion("Biaodi >", value, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiGreaterThanOrEqualTo(String value) {
            addCriterion("Biaodi >=", value, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiLessThan(String value) {
            addCriterion("Biaodi <", value, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiLessThanOrEqualTo(String value) {
            addCriterion("Biaodi <=", value, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiLike(String value) {
            addCriterion("Biaodi like", value, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiNotLike(String value) {
            addCriterion("Biaodi not like", value, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiIn(List<String> values) {
            addCriterion("Biaodi in", values, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiNotIn(List<String> values) {
            addCriterion("Biaodi not in", values, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiBetween(String value1, String value2) {
            addCriterion("Biaodi between", value1, value2, "biaodi");
            return (Criteria) this;
        }

        public Criteria andBiaodiNotBetween(String value1, String value2) {
            addCriterion("Biaodi not between", value1, value2, "biaodi");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("Status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("Status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOrgnoIsNull() {
            addCriterion("Orgno is null");
            return (Criteria) this;
        }

        public Criteria andOrgnoIsNotNull() {
            addCriterion("Orgno is not null");
            return (Criteria) this;
        }

        public Criteria andOrgnoEqualTo(String value) {
            addCriterion("Orgno =", value, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoNotEqualTo(String value) {
            addCriterion("Orgno <>", value, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoGreaterThan(String value) {
            addCriterion("Orgno >", value, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoGreaterThanOrEqualTo(String value) {
            addCriterion("Orgno >=", value, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoLessThan(String value) {
            addCriterion("Orgno <", value, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoLessThanOrEqualTo(String value) {
            addCriterion("Orgno <=", value, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoLike(String value) {
            addCriterion("Orgno like", value, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoNotLike(String value) {
            addCriterion("Orgno not like", value, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoIn(List<String> values) {
            addCriterion("Orgno in", values, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoNotIn(List<String> values) {
            addCriterion("Orgno not in", values, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoBetween(String value1, String value2) {
            addCriterion("Orgno between", value1, value2, "orgno");
            return (Criteria) this;
        }

        public Criteria andOrgnoNotBetween(String value1, String value2) {
            addCriterion("Orgno not between", value1, value2, "orgno");
            return (Criteria) this;
        }

        public Criteria andUniquenoIsNull() {
            addCriterion("Uniqueno is null");
            return (Criteria) this;
        }

        public Criteria andUniquenoIsNotNull() {
            addCriterion("Uniqueno is not null");
            return (Criteria) this;
        }

        public Criteria andUniquenoEqualTo(String value) {
            addCriterion("Uniqueno =", value, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoNotEqualTo(String value) {
            addCriterion("Uniqueno <>", value, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoGreaterThan(String value) {
            addCriterion("Uniqueno >", value, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoGreaterThanOrEqualTo(String value) {
            addCriterion("Uniqueno >=", value, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoLessThan(String value) {
            addCriterion("Uniqueno <", value, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoLessThanOrEqualTo(String value) {
            addCriterion("Uniqueno <=", value, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoLike(String value) {
            addCriterion("Uniqueno like", value, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoNotLike(String value) {
            addCriterion("Uniqueno not like", value, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoIn(List<String> values) {
            addCriterion("Uniqueno in", values, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoNotIn(List<String> values) {
            addCriterion("Uniqueno not in", values, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoBetween(String value1, String value2) {
            addCriterion("Uniqueno between", value1, value2, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andUniquenoNotBetween(String value1, String value2) {
            addCriterion("Uniqueno not between", value1, value2, "uniqueno");
            return (Criteria) this;
        }

        public Criteria andOwnernameIsNull() {
            addCriterion("Ownername is null");
            return (Criteria) this;
        }

        public Criteria andOwnernameIsNotNull() {
            addCriterion("Ownername is not null");
            return (Criteria) this;
        }

        public Criteria andOwnernameEqualTo(String value) {
            addCriterion("Ownername =", value, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameNotEqualTo(String value) {
            addCriterion("Ownername <>", value, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameGreaterThan(String value) {
            addCriterion("Ownername >", value, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameGreaterThanOrEqualTo(String value) {
            addCriterion("Ownername >=", value, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameLessThan(String value) {
            addCriterion("Ownername <", value, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameLessThanOrEqualTo(String value) {
            addCriterion("Ownername <=", value, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameLike(String value) {
            addCriterion("Ownername like", value, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameNotLike(String value) {
            addCriterion("Ownername not like", value, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameIn(List<String> values) {
            addCriterion("Ownername in", values, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameNotIn(List<String> values) {
            addCriterion("Ownername not in", values, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameBetween(String value1, String value2) {
            addCriterion("Ownername between", value1, value2, "ownername");
            return (Criteria) this;
        }

        public Criteria andOwnernameNotBetween(String value1, String value2) {
            addCriterion("Ownername not between", value1, value2, "ownername");
            return (Criteria) this;
        }

        public Criteria andExecutegovIsNull() {
            addCriterion("Executegov is null");
            return (Criteria) this;
        }

        public Criteria andExecutegovIsNotNull() {
            addCriterion("Executegov is not null");
            return (Criteria) this;
        }

        public Criteria andExecutegovEqualTo(String value) {
            addCriterion("Executegov =", value, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovNotEqualTo(String value) {
            addCriterion("Executegov <>", value, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovGreaterThan(String value) {
            addCriterion("Executegov >", value, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovGreaterThanOrEqualTo(String value) {
            addCriterion("Executegov >=", value, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovLessThan(String value) {
            addCriterion("Executegov <", value, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovLessThanOrEqualTo(String value) {
            addCriterion("Executegov <=", value, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovLike(String value) {
            addCriterion("Executegov like", value, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovNotLike(String value) {
            addCriterion("Executegov not like", value, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovIn(List<String> values) {
            addCriterion("Executegov in", values, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovNotIn(List<String> values) {
            addCriterion("Executegov not in", values, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovBetween(String value1, String value2) {
            addCriterion("Executegov between", value1, value2, "executegov");
            return (Criteria) this;
        }

        public Criteria andExecutegovNotBetween(String value1, String value2) {
            addCriterion("Executegov not between", value1, value2, "executegov");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("Province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("Province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("Province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("Province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("Province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("Province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("Province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("Province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("Province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("Province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("Province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("Province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("Province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("Province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteIsNull() {
            addCriterion("Executeunite is null");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteIsNotNull() {
            addCriterion("Executeunite is not null");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteEqualTo(String value) {
            addCriterion("Executeunite =", value, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteNotEqualTo(String value) {
            addCriterion("Executeunite <>", value, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteGreaterThan(String value) {
            addCriterion("Executeunite >", value, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteGreaterThanOrEqualTo(String value) {
            addCriterion("Executeunite >=", value, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteLessThan(String value) {
            addCriterion("Executeunite <", value, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteLessThanOrEqualTo(String value) {
            addCriterion("Executeunite <=", value, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteLike(String value) {
            addCriterion("Executeunite like", value, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteNotLike(String value) {
            addCriterion("Executeunite not like", value, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteIn(List<String> values) {
            addCriterion("Executeunite in", values, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteNotIn(List<String> values) {
            addCriterion("Executeunite not in", values, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteBetween(String value1, String value2) {
            addCriterion("Executeunite between", value1, value2, "executeunite");
            return (Criteria) this;
        }

        public Criteria andExecuteuniteNotBetween(String value1, String value2) {
            addCriterion("Executeunite not between", value1, value2, "executeunite");
            return (Criteria) this;
        }

        public Criteria andYiwuIsNull() {
            addCriterion("Yiwu is null");
            return (Criteria) this;
        }

        public Criteria andYiwuIsNotNull() {
            addCriterion("Yiwu is not null");
            return (Criteria) this;
        }

        public Criteria andYiwuEqualTo(String value) {
            addCriterion("Yiwu =", value, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuNotEqualTo(String value) {
            addCriterion("Yiwu <>", value, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuGreaterThan(String value) {
            addCriterion("Yiwu >", value, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuGreaterThanOrEqualTo(String value) {
            addCriterion("Yiwu >=", value, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuLessThan(String value) {
            addCriterion("Yiwu <", value, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuLessThanOrEqualTo(String value) {
            addCriterion("Yiwu <=", value, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuLike(String value) {
            addCriterion("Yiwu like", value, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuNotLike(String value) {
            addCriterion("Yiwu not like", value, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuIn(List<String> values) {
            addCriterion("Yiwu in", values, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuNotIn(List<String> values) {
            addCriterion("Yiwu not in", values, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuBetween(String value1, String value2) {
            addCriterion("Yiwu between", value1, value2, "yiwu");
            return (Criteria) this;
        }

        public Criteria andYiwuNotBetween(String value1, String value2) {
            addCriterion("Yiwu not between", value1, value2, "yiwu");
            return (Criteria) this;
        }

        public Criteria andExecutestatusIsNull() {
            addCriterion("Executestatus is null");
            return (Criteria) this;
        }

        public Criteria andExecutestatusIsNotNull() {
            addCriterion("Executestatus is not null");
            return (Criteria) this;
        }

        public Criteria andExecutestatusEqualTo(String value) {
            addCriterion("Executestatus =", value, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusNotEqualTo(String value) {
            addCriterion("Executestatus <>", value, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusGreaterThan(String value) {
            addCriterion("Executestatus >", value, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusGreaterThanOrEqualTo(String value) {
            addCriterion("Executestatus >=", value, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusLessThan(String value) {
            addCriterion("Executestatus <", value, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusLessThanOrEqualTo(String value) {
            addCriterion("Executestatus <=", value, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusLike(String value) {
            addCriterion("Executestatus like", value, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusNotLike(String value) {
            addCriterion("Executestatus not like", value, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusIn(List<String> values) {
            addCriterion("Executestatus in", values, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusNotIn(List<String> values) {
            addCriterion("Executestatus not in", values, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusBetween(String value1, String value2) {
            addCriterion("Executestatus between", value1, value2, "executestatus");
            return (Criteria) this;
        }

        public Criteria andExecutestatusNotBetween(String value1, String value2) {
            addCriterion("Executestatus not between", value1, value2, "executestatus");
            return (Criteria) this;
        }

        public Criteria andActionremarkIsNull() {
            addCriterion("Actionremark is null");
            return (Criteria) this;
        }

        public Criteria andActionremarkIsNotNull() {
            addCriterion("Actionremark is not null");
            return (Criteria) this;
        }

        public Criteria andActionremarkEqualTo(String value) {
            addCriterion("Actionremark =", value, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkNotEqualTo(String value) {
            addCriterion("Actionremark <>", value, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkGreaterThan(String value) {
            addCriterion("Actionremark >", value, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkGreaterThanOrEqualTo(String value) {
            addCriterion("Actionremark >=", value, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkLessThan(String value) {
            addCriterion("Actionremark <", value, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkLessThanOrEqualTo(String value) {
            addCriterion("Actionremark <=", value, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkLike(String value) {
            addCriterion("Actionremark like", value, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkNotLike(String value) {
            addCriterion("Actionremark not like", value, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkIn(List<String> values) {
            addCriterion("Actionremark in", values, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkNotIn(List<String> values) {
            addCriterion("Actionremark not in", values, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkBetween(String value1, String value2) {
            addCriterion("Actionremark between", value1, value2, "actionremark");
            return (Criteria) this;
        }

        public Criteria andActionremarkNotBetween(String value1, String value2) {
            addCriterion("Actionremark not between", value1, value2, "actionremark");
            return (Criteria) this;
        }

        public Criteria andPublicdateIsNull() {
            addCriterion("Publicdate is null");
            return (Criteria) this;
        }

        public Criteria andPublicdateIsNotNull() {
            addCriterion("Publicdate is not null");
            return (Criteria) this;
        }

        public Criteria andPublicdateEqualTo(String value) {
            addCriterion("Publicdate =", value, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateNotEqualTo(String value) {
            addCriterion("Publicdate <>", value, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateGreaterThan(String value) {
            addCriterion("Publicdate >", value, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateGreaterThanOrEqualTo(String value) {
            addCriterion("Publicdate >=", value, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateLessThan(String value) {
            addCriterion("Publicdate <", value, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateLessThanOrEqualTo(String value) {
            addCriterion("Publicdate <=", value, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateLike(String value) {
            addCriterion("Publicdate like", value, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateNotLike(String value) {
            addCriterion("Publicdate not like", value, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateIn(List<String> values) {
            addCriterion("Publicdate in", values, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateNotIn(List<String> values) {
            addCriterion("Publicdate not in", values, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateBetween(String value1, String value2) {
            addCriterion("Publicdate between", value1, value2, "publicdate");
            return (Criteria) this;
        }

        public Criteria andPublicdateNotBetween(String value1, String value2) {
            addCriterion("Publicdate not between", value1, value2, "publicdate");
            return (Criteria) this;
        }

        public Criteria andFollowsIsNull() {
            addCriterion("Follows is null");
            return (Criteria) this;
        }

        public Criteria andFollowsIsNotNull() {
            addCriterion("Follows is not null");
            return (Criteria) this;
        }

        public Criteria andFollowsEqualTo(String value) {
            addCriterion("Follows =", value, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsNotEqualTo(String value) {
            addCriterion("Follows <>", value, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsGreaterThan(String value) {
            addCriterion("Follows >", value, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsGreaterThanOrEqualTo(String value) {
            addCriterion("Follows >=", value, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsLessThan(String value) {
            addCriterion("Follows <", value, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsLessThanOrEqualTo(String value) {
            addCriterion("Follows <=", value, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsLike(String value) {
            addCriterion("Follows like", value, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsNotLike(String value) {
            addCriterion("Follows not like", value, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsIn(List<String> values) {
            addCriterion("Follows in", values, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsNotIn(List<String> values) {
            addCriterion("Follows not in", values, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsBetween(String value1, String value2) {
            addCriterion("Follows between", value1, value2, "follows");
            return (Criteria) this;
        }

        public Criteria andFollowsNotBetween(String value1, String value2) {
            addCriterion("Follows not between", value1, value2, "follows");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("Age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("Age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(String value) {
            addCriterion("Age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(String value) {
            addCriterion("Age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(String value) {
            addCriterion("Age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(String value) {
            addCriterion("Age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(String value) {
            addCriterion("Age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(String value) {
            addCriterion("Age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLike(String value) {
            addCriterion("Age like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotLike(String value) {
            addCriterion("Age not like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<String> values) {
            addCriterion("Age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<String> values) {
            addCriterion("Age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(String value1, String value2) {
            addCriterion("Age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(String value1, String value2) {
            addCriterion("Age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andSexyIsNull() {
            addCriterion("Sexy is null");
            return (Criteria) this;
        }

        public Criteria andSexyIsNotNull() {
            addCriterion("Sexy is not null");
            return (Criteria) this;
        }

        public Criteria andSexyEqualTo(String value) {
            addCriterion("Sexy =", value, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyNotEqualTo(String value) {
            addCriterion("Sexy <>", value, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyGreaterThan(String value) {
            addCriterion("Sexy >", value, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyGreaterThanOrEqualTo(String value) {
            addCriterion("Sexy >=", value, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyLessThan(String value) {
            addCriterion("Sexy <", value, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyLessThanOrEqualTo(String value) {
            addCriterion("Sexy <=", value, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyLike(String value) {
            addCriterion("Sexy like", value, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyNotLike(String value) {
            addCriterion("Sexy not like", value, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyIn(List<String> values) {
            addCriterion("Sexy in", values, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyNotIn(List<String> values) {
            addCriterion("Sexy not in", values, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyBetween(String value1, String value2) {
            addCriterion("Sexy between", value1, value2, "sexy");
            return (Criteria) this;
        }

        public Criteria andSexyNotBetween(String value1, String value2) {
            addCriterion("Sexy not between", value1, value2, "sexy");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("Createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("Createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(String value) {
            addCriterion("Createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(String value) {
            addCriterion("Createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(String value) {
            addCriterion("Createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(String value) {
            addCriterion("Createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(String value) {
            addCriterion("Createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(String value) {
            addCriterion("Createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLike(String value) {
            addCriterion("Createdate like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotLike(String value) {
            addCriterion("Createdate not like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<String> values) {
            addCriterion("Createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<String> values) {
            addCriterion("Createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(String value1, String value2) {
            addCriterion("Createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(String value1, String value2) {
            addCriterion("Createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("Updatedate is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("Updatedate is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(String value) {
            addCriterion("Updatedate =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(String value) {
            addCriterion("Updatedate <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(String value) {
            addCriterion("Updatedate >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(String value) {
            addCriterion("Updatedate >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(String value) {
            addCriterion("Updatedate <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(String value) {
            addCriterion("Updatedate <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLike(String value) {
            addCriterion("Updatedate like", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotLike(String value) {
            addCriterion("Updatedate not like", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<String> values) {
            addCriterion("Updatedate in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<String> values) {
            addCriterion("Updatedate not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(String value1, String value2) {
            addCriterion("Updatedate between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(String value1, String value2) {
            addCriterion("Updatedate not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andExecutenoIsNull() {
            addCriterion("Executeno is null");
            return (Criteria) this;
        }

        public Criteria andExecutenoIsNotNull() {
            addCriterion("Executeno is not null");
            return (Criteria) this;
        }

        public Criteria andExecutenoEqualTo(String value) {
            addCriterion("Executeno =", value, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoNotEqualTo(String value) {
            addCriterion("Executeno <>", value, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoGreaterThan(String value) {
            addCriterion("Executeno >", value, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoGreaterThanOrEqualTo(String value) {
            addCriterion("Executeno >=", value, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoLessThan(String value) {
            addCriterion("Executeno <", value, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoLessThanOrEqualTo(String value) {
            addCriterion("Executeno <=", value, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoLike(String value) {
            addCriterion("Executeno like", value, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoNotLike(String value) {
            addCriterion("Executeno not like", value, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoIn(List<String> values) {
            addCriterion("Executeno in", values, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoNotIn(List<String> values) {
            addCriterion("Executeno not in", values, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoBetween(String value1, String value2) {
            addCriterion("Executeno between", value1, value2, "executeno");
            return (Criteria) this;
        }

        public Criteria andExecutenoNotBetween(String value1, String value2) {
            addCriterion("Executeno not between", value1, value2, "executeno");
            return (Criteria) this;
        }

        public Criteria andPerformedpartIsNull() {
            addCriterion("Performedpart is null");
            return (Criteria) this;
        }

        public Criteria andPerformedpartIsNotNull() {
            addCriterion("Performedpart is not null");
            return (Criteria) this;
        }

        public Criteria andPerformedpartEqualTo(String value) {
            addCriterion("Performedpart =", value, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartNotEqualTo(String value) {
            addCriterion("Performedpart <>", value, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartGreaterThan(String value) {
            addCriterion("Performedpart >", value, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartGreaterThanOrEqualTo(String value) {
            addCriterion("Performedpart >=", value, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartLessThan(String value) {
            addCriterion("Performedpart <", value, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartLessThanOrEqualTo(String value) {
            addCriterion("Performedpart <=", value, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartLike(String value) {
            addCriterion("Performedpart like", value, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartNotLike(String value) {
            addCriterion("Performedpart not like", value, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartIn(List<String> values) {
            addCriterion("Performedpart in", values, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartNotIn(List<String> values) {
            addCriterion("Performedpart not in", values, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartBetween(String value1, String value2) {
            addCriterion("Performedpart between", value1, value2, "performedpart");
            return (Criteria) this;
        }

        public Criteria andPerformedpartNotBetween(String value1, String value2) {
            addCriterion("Performedpart not between", value1, value2, "performedpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartIsNull() {
            addCriterion("Unperformpart is null");
            return (Criteria) this;
        }

        public Criteria andUnperformpartIsNotNull() {
            addCriterion("Unperformpart is not null");
            return (Criteria) this;
        }

        public Criteria andUnperformpartEqualTo(String value) {
            addCriterion("Unperformpart =", value, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartNotEqualTo(String value) {
            addCriterion("Unperformpart <>", value, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartGreaterThan(String value) {
            addCriterion("Unperformpart >", value, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartGreaterThanOrEqualTo(String value) {
            addCriterion("Unperformpart >=", value, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartLessThan(String value) {
            addCriterion("Unperformpart <", value, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartLessThanOrEqualTo(String value) {
            addCriterion("Unperformpart <=", value, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartLike(String value) {
            addCriterion("Unperformpart like", value, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartNotLike(String value) {
            addCriterion("Unperformpart not like", value, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartIn(List<String> values) {
            addCriterion("Unperformpart in", values, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartNotIn(List<String> values) {
            addCriterion("Unperformpart not in", values, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartBetween(String value1, String value2) {
            addCriterion("Unperformpart between", value1, value2, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andUnperformpartNotBetween(String value1, String value2) {
            addCriterion("Unperformpart not between", value1, value2, "unperformpart");
            return (Criteria) this;
        }

        public Criteria andIspersonIsNull() {
            addCriterion("Isperson is null");
            return (Criteria) this;
        }

        public Criteria andIspersonIsNotNull() {
            addCriterion("Isperson is not null");
            return (Criteria) this;
        }

        public Criteria andIspersonEqualTo(String value) {
            addCriterion("Isperson =", value, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonNotEqualTo(String value) {
            addCriterion("Isperson <>", value, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonGreaterThan(String value) {
            addCriterion("Isperson >", value, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonGreaterThanOrEqualTo(String value) {
            addCriterion("Isperson >=", value, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonLessThan(String value) {
            addCriterion("Isperson <", value, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonLessThanOrEqualTo(String value) {
            addCriterion("Isperson <=", value, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonLike(String value) {
            addCriterion("Isperson like", value, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonNotLike(String value) {
            addCriterion("Isperson not like", value, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonIn(List<String> values) {
            addCriterion("Isperson in", values, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonNotIn(List<String> values) {
            addCriterion("Isperson not in", values, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonBetween(String value1, String value2) {
            addCriterion("Isperson between", value1, value2, "isperson");
            return (Criteria) this;
        }

        public Criteria andIspersonNotBetween(String value1, String value2) {
            addCriterion("Isperson not between", value1, value2, "isperson");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table breakonespromise
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 14 11:01:53 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}