package com.hoomsun.aoqian;

public class Breakonespromise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.a1
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String a1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Id
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Sourceid
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String sourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Name
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Liandate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String liandate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Anno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String anno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Biaodi
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String biaodi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Status
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Orgno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Uniqueno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String uniqueno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Ownername
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String ownername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Executegov
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String executegov;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Province
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Executeunite
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String executeunite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Yiwu
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String yiwu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Executestatus
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String executestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Actionremark
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String actionremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Publicdate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String publicdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Follows
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String follows;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Age
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Sexy
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String sexy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Createdate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Updatedate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Executeno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String executeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Performedpart
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String performedpart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Unperformpart
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String unperformpart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakonespromise.Isperson
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    private String isperson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.a1
     *
     * @return the value of breakonespromise.a1
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getA1() {
        return a1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.a1
     *
     * @param a1 the value for breakonespromise.a1
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setA1(String a1) {
        this.a1 = a1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Id
     *
     * @return the value of breakonespromise.Id
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Id
     *
     * @param id the value for breakonespromise.Id
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Sourceid
     *
     * @return the value of breakonespromise.Sourceid
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Sourceid
     *
     * @param sourceid the value for breakonespromise.Sourceid
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setSourceid(String sourceid) {
        this.sourceid = sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Name
     *
     * @return the value of breakonespromise.Name
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Name
     *
     * @param name the value for breakonespromise.Name
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Liandate
     *
     * @return the value of breakonespromise.Liandate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getLiandate() {
        return liandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Liandate
     *
     * @param liandate the value for breakonespromise.Liandate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setLiandate(String liandate) {
        this.liandate = liandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Anno
     *
     * @return the value of breakonespromise.Anno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getAnno() {
        return anno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Anno
     *
     * @param anno the value for breakonespromise.Anno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setAnno(String anno) {
        this.anno = anno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Biaodi
     *
     * @return the value of breakonespromise.Biaodi
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getBiaodi() {
        return biaodi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Biaodi
     *
     * @param biaodi the value for breakonespromise.Biaodi
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setBiaodi(String biaodi) {
        this.biaodi = biaodi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Status
     *
     * @return the value of breakonespromise.Status
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Status
     *
     * @param status the value for breakonespromise.Status
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Orgno
     *
     * @return the value of breakonespromise.Orgno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Orgno
     *
     * @param orgno the value for breakonespromise.Orgno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Uniqueno
     *
     * @return the value of breakonespromise.Uniqueno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getUniqueno() {
        return uniqueno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Uniqueno
     *
     * @param uniqueno the value for breakonespromise.Uniqueno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setUniqueno(String uniqueno) {
        this.uniqueno = uniqueno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Ownername
     *
     * @return the value of breakonespromise.Ownername
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getOwnername() {
        return ownername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Ownername
     *
     * @param ownername the value for breakonespromise.Ownername
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setOwnername(String ownername) {
        this.ownername = ownername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Executegov
     *
     * @return the value of breakonespromise.Executegov
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getExecutegov() {
        return executegov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Executegov
     *
     * @param executegov the value for breakonespromise.Executegov
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setExecutegov(String executegov) {
        this.executegov = executegov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Province
     *
     * @return the value of breakonespromise.Province
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Province
     *
     * @param province the value for breakonespromise.Province
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Executeunite
     *
     * @return the value of breakonespromise.Executeunite
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getExecuteunite() {
        return executeunite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Executeunite
     *
     * @param executeunite the value for breakonespromise.Executeunite
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setExecuteunite(String executeunite) {
        this.executeunite = executeunite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Yiwu
     *
     * @return the value of breakonespromise.Yiwu
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getYiwu() {
        return yiwu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Yiwu
     *
     * @param yiwu the value for breakonespromise.Yiwu
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setYiwu(String yiwu) {
        this.yiwu = yiwu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Executestatus
     *
     * @return the value of breakonespromise.Executestatus
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getExecutestatus() {
        return executestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Executestatus
     *
     * @param executestatus the value for breakonespromise.Executestatus
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setExecutestatus(String executestatus) {
        this.executestatus = executestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Actionremark
     *
     * @return the value of breakonespromise.Actionremark
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getActionremark() {
        return actionremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Actionremark
     *
     * @param actionremark the value for breakonespromise.Actionremark
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setActionremark(String actionremark) {
        this.actionremark = actionremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Publicdate
     *
     * @return the value of breakonespromise.Publicdate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getPublicdate() {
        return publicdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Publicdate
     *
     * @param publicdate the value for breakonespromise.Publicdate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setPublicdate(String publicdate) {
        this.publicdate = publicdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Follows
     *
     * @return the value of breakonespromise.Follows
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getFollows() {
        return follows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Follows
     *
     * @param follows the value for breakonespromise.Follows
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setFollows(String follows) {
        this.follows = follows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Age
     *
     * @return the value of breakonespromise.Age
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Age
     *
     * @param age the value for breakonespromise.Age
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Sexy
     *
     * @return the value of breakonespromise.Sexy
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getSexy() {
        return sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Sexy
     *
     * @param sexy the value for breakonespromise.Sexy
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setSexy(String sexy) {
        this.sexy = sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Createdate
     *
     * @return the value of breakonespromise.Createdate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Createdate
     *
     * @param createdate the value for breakonespromise.Createdate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Updatedate
     *
     * @return the value of breakonespromise.Updatedate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Updatedate
     *
     * @param updatedate the value for breakonespromise.Updatedate
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setUpdatedate(String updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Executeno
     *
     * @return the value of breakonespromise.Executeno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getExecuteno() {
        return executeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Executeno
     *
     * @param executeno the value for breakonespromise.Executeno
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setExecuteno(String executeno) {
        this.executeno = executeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Performedpart
     *
     * @return the value of breakonespromise.Performedpart
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getPerformedpart() {
        return performedpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Performedpart
     *
     * @param performedpart the value for breakonespromise.Performedpart
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setPerformedpart(String performedpart) {
        this.performedpart = performedpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Unperformpart
     *
     * @return the value of breakonespromise.Unperformpart
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getUnperformpart() {
        return unperformpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Unperformpart
     *
     * @param unperformpart the value for breakonespromise.Unperformpart
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setUnperformpart(String unperformpart) {
        this.unperformpart = unperformpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakonespromise.Isperson
     *
     * @return the value of breakonespromise.Isperson
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public String getIsperson() {
        return isperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakonespromise.Isperson
     *
     * @param isperson the value for breakonespromise.Isperson
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    public void setIsperson(String isperson) {
        this.isperson = isperson;
    }
}