package com.hoomsun.aoqian;

import com.hoomsun.aoqian.Breakonespromise;
import com.hoomsun.aoqian.BreakonespromiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BreakonespromiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    int countByExample(BreakonespromiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    int deleteByExample(BreakonespromiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    int insert(Breakonespromise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    int insertSelective(Breakonespromise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    List<Breakonespromise> selectByExample(BreakonespromiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") Breakonespromise record, @Param("example") BreakonespromiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakonespromise
     *
     * @mbggenerated Thu Jul 14 11:01:53 CST 2016
     */
    int updateByExample(@Param("record") Breakonespromise record, @Param("example") BreakonespromiseExample example);
}